steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-east1-docker.pkg.dev/qwiklabs-gcp-01-f820141f45bf/cepf-repo/app', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-east1-docker.pkg.dev/qwiklabs-gcp-01-f820141f45bf/cepf-repo/app']